### ISSUE TITLE
dissemin API returns null

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCApi#14]
The dissemin API is returning null in an unexpected call:
```
working: 20191119_CalWORKsCashGrantCaseloadMovementReport_publications.json
Traceback (most recent call last):
  File "./x.py", line 74, in gather_pdf
    meta = api.publication_lookup(doi)
  File "/Users/paco/src/venv/lib/python3.6/site-packages/richcontext/scholapi/scholapi.py", line 195, in publication_lookup
    meta = json.loads(requests.get(url).text)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Do changes in oil prices affect welfare programs? Evidence from Kern County
10.1016/j.eneco.2017.06.013
dissemin
```

**Comment by ceteri** [comment]
cannot replicate

**Comment by ceteri** [comment]
We're seeing intermittent error responses from the `dissemin` servers.

Added code to handle an error response defensively.
