### ISSUE TITLE
KG errors during Step 3

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCApi#30]
```
20190717_usda_wic_publications:  78%|#######7  | 477/615 [09:09<02:41,  1.17s/it]Traceback (most recent call last):
  File "/home/ceteri/RCGraph/venv/lib/python3.6/site-packages/richcontext/scholapi/scholapi.py", line 264, in publication_lookup
    raise Exception(str(meta))
Exception: {'error': 404, 'message': 'The paper you requested could not be found.'}
ERROR: 10.1542/peds.2017-3716
Traceback (most recent call last):
  File "/home/ceteri/RCGraph/venv/lib/python3.6/site-packages/richcontext/scholapi/scholapi.py", line 264, in publication_lookup
    raise Exception(str(meta))
```

**Comment by ceteri** [comment]
Also,

```
20191119_PublicSchools_publica:  25%|##5       | 5/20 [00:06<00:18,  1.25s/it]Traceback (most recent call last):
  File "./run_step3.py", line 40, in gather_pdf
    meta = api.publication_lookup(doi)
  File "/home/ceteri/RCGraph/venv/lib/python3.6/site-packages/richcontext/scholapi/scholapi.py", line 234, in publication_lookup
    meta = json.loads(requests.get(url).text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ceteri** [comment]
Also,

```
ERROR: 10.1023/a:1016694701704
Traceback (most recent call last):
  File "/home/ceteri/RCGraph/venv/lib/python3.6/site-packages/richcontext/scholapi/scholapi.py", line 257, in publication_lookup
    meta = json.loads(requests.get(url).text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 6 column 1 (char 5)
```
